---
# defaults file for create_volume_snapshots

# OpenShift Cluster login information to connect to the OpenShift Cluster
# Note: Make sure the API token is latest and is not expired
oc_api_url: "https://api.example.openshift.com:6443"
oc_api_token: "<your_api_token>"

# Namespace where the source PVCs live and VolumeSnapshots will be created
pvc_namespace: test-project

# VolumeSnapshotClass to use (name must refer to an existing VolumeSnapshotClass)
vol_snapshot_class_specs:
  name: test-ontap-snapshot-class

# VolumeSnapshot specifications
# Define the VolumeSnapshots to be created from existing PVCs in pvc_namespace.
volume_snapshot_specs:
  - { snapshot_name: nfs-pvc-snapshot-1, pvc_name: test-nfs-pvc-1 }
  - { snapshot_name: nfs-flexgroup-pvc-snapshot-1, pvc_name: test-nfs-flexgroup-pvc-1 }
  - { snapshot_name: iscsi-pvc-snapshot-1, pvc_name: test-iscsi-pvc }
  - { snapshot_name: nvme-tcp-pvc-snapshot-1, pvc_name: test-nvme-tcp-pvc }
  - { snapshot_name: fcp-pvc-snapshot-1, pvc_name: test-fcp-pvc }
