---
# Create a VolumeSnapshotClass for NetApp Trident snapshot operations.

- name: Verify required variables are defined and not empty
  ansible.builtin.fail:
    msg: "{{ item }} is not defined or empty"
  when: "vars[item] is not defined or (vars[item] | default('') | string | length == 0)"
  loop:
    - create_volume_snapshotclass_oc_api_url
    - create_volume_snapshotclass_oc_api_token
    - create_volume_snapshotclass_vol_snapshot_class_specs

- name: Define anchor for OpenShift/Kubernetes API login info
  ansible.builtin.set_fact:
    k8s_auth: &k8s_auth
      host: "{{ create_volume_snapshotclass_oc_api_url | default(omit) }}"
      api_key: "{{ create_volume_snapshotclass_oc_api_token | default(omit) }}"
      validate_certs: "{{ create_volume_snapshotclass_validate_certs | default(false) }}"

- name: Verify required fields in create_volume_snapshotclass_vol_snapshot_class_specs
  ansible.builtin.fail:
    msg: "create_volume_snapshotclass_vol_snapshot_class_specs.{{ item }} is not defined or empty"
  when:
    - create_volume_snapshotclass_vol_snapshot_class_specs[item] is not defined
      or (create_volume_snapshotclass_vol_snapshot_class_specs[item] | default('') | string | length == 0)
  loop:
    - name

# Create VolumeSnapshotClass for snapshot operations
- name: Create VolumeSnapshotClass for snapshot operations
  kubernetes.core.k8s:
    <<: *k8s_auth
    state: present
    definition:
      apiVersion: snapshot.storage.k8s.io/v1
      kind: VolumeSnapshotClass
      metadata:
        name: "{{ create_volume_snapshotclass_vol_snapshot_class_specs.name }}"
      driver: csi.trident.netapp.io
      deletionPolicy: "{{ create_volume_snapshotclass_vol_snapshot_class_specs.deletion_policy | default('Delete') }}"
  tags:
    - k8s_create_volume_snapshot_class
