---
# defaults file for create_storageclass

create_storageclass_configure_nfs: false
create_storageclass_configure_nfs_flexgroup: false
create_storageclass_configure_iscsi: false
create_storageclass_configure_fcp: false
create_storageclass_configure_nvme_tcp: false
