---
# defaults file for set_default_storageclass

set_default_storageclass_configure_nfs_flexgroup: false
set_default_storageclass_configure_iscsi: false
set_default_storageclass_configure_fcp: false
set_default_storageclass_configure_nvme_tcp: false
