---
# defaults file for create_pvcs

create_pvcs_configure_nfs: false
create_pvcs_configure_nfs_flexgroup: false
create_pvcs_configure_iscsi: false
create_pvcs_configure_fcp: false
create_pvcs_configure_nvme_tcp: false
