---
# defaults file for delete_pvcs

delete_pvcs_configure_nfs: false
delete_pvcs_configure_nfs_flexgroup: false
delete_pvcs_configure_iscsi: false
delete_pvcs_configure_fcp: false
delete_pvcs_configure_nvme_tcp: false
