---
# defaults file for delete_storageclass

# OpenShift Cluster login information to connect to the OpenShift Cluster
# Note: Make sure the API token is latest and is not expired
oc_api_url: "https://api.example.openshift.com:6443"
oc_api_token: "<your_api_token>"

configure_nfs: true
configure_nfs_flexgroup: true
configure_iscsi: true
configure_fcp: true
configure_nvme_tcp: true

# StorageClasses to delete per backend (sc_name must match the previously created StorageClass)
nfs_specs:
  sc_name: ontap-nfs-sc

nfs_flexgroup_specs:
  sc_name: ontap-nfs-flexgroup-sc

iscsi_specs:
  sc_name: ontap-iscsi-sc

nvme_tcp_specs:
  sc_name: ontap-nvme-tcp-sc

fcp_specs:
  sc_name: ontap-fcp-sc
